server:
  port: 8000

#https://stackoverflow.com/questions/54117061/springcloudgateway-log-incoming-request-url-and-corresponding-route-uri
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
          filters:
            #            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - StripPrefix=1
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/ratings/**
          filters:
            - StripPrefix=1
info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: ${EUREKA_SERVER:http://localhost:8671/eureka}
  healthcheck:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
